from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from tempfile import TemporaryDirectory

from git import Repo

from agentsystem.adapters.config_reader import RepoBConfigReader
from agentsystem.adapters.git_adapter import GitAdapter
from agentsystem.adapters.github_pr import GitHubPullRequestAdapter
from agentsystem.adapters.shell_executor import ShellExecutor
from agentsystem.core.settings import Settings


BRANCH_SLUG = "demo-agent-snapshot"
COMMIT_MESSAGE = "feat: enrich agent snapshot mock view (Repo A demo)"
PR_TITLE = "[Auto] Enrich agent snapshot mock view"
PR_BODY = (
    "This pull request was generated by Repo A. "
    "It enriches the mock agent snapshot payload and renders a positions table "
    "on the agent observation page."
)

UPDATED_AGENT_REGISTRY = """from __future__ import annotations

from dataclasses import dataclass

from schemas.common import AcceptedResponse
from schemas.command import AgentRegisterRequest, HeartbeatRequest
from schemas.agent import AgentSnapshot, Position


@dataclass(slots=True)
class AgentRegistryService:
    default_world_id: str

    def register(self, payload: AgentRegisterRequest) -> AcceptedResponse:
        return AcceptedResponse(status="accepted", task_id=f"register::{payload.agent_id}")

    def heartbeat(self, agent_id: str, payload: HeartbeatRequest) -> AcceptedResponse:
        return AcceptedResponse(status="accepted", task_id=f"heartbeat::{agent_id}::{payload.heartbeat_at}")

    def snapshot(self, agent_id: str) -> AgentSnapshot:
        return AgentSnapshot(
            agent_id=agent_id,
            status="active",
            equity=105000.0,
            cash=50000.0,
            drawdown=0.05,
            tags=["trend", "swing"],
            positions=[
                Position(symbol="600519.SH", qty=100, avg_cost=1680.0),
                Position(symbol="000001.SZ", qty=300, avg_cost=12.45),
                Position(symbol="AAPL", qty=25, avg_cost=182.3),
            ],
        )
"""

UPDATED_AGENT_PAGE = """import { env } from "@/env";

interface Position {
  symbol: string;
  qty: number;
  avg_cost: number;
}

interface AgentSnapshot {
  agent_id: string;
  equity: number;
  cash: number;
  status: string;
  tags: string[];
  positions: Position[];
}

export default async function AgentPage({
  params,
}: {
  params: Promise<{ agentId: string }>;
}) {
  const { agentId } = await params;
  const response = await fetch(`${env.apiBaseUrl}/api/v1/agents/${agentId}/snapshot`, {
    cache: "no-store",
  });
  const data = (await response.json()) as AgentSnapshot;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="mb-2 text-2xl font-bold">Agent: {agentId}</h1>
        <p className="text-sm text-gray-500">
          Status: <span className="font-medium text-gray-900">{data.status}</span>
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="rounded-lg border p-4">
          <div className="text-sm text-gray-500">Equity</div>
          <div className="text-2xl font-bold">¥{data.equity.toLocaleString()}</div>
        </div>
        <div className="rounded-lg border p-4">
          <div className="text-sm text-gray-500">Cash</div>
          <div className="text-2xl font-bold">¥{data.cash.toLocaleString()}</div>
        </div>
      </div>

      <div className="rounded-lg border p-4">
        <div className="mb-3 flex items-center gap-2">
          <h2 className="text-lg font-semibold">Tags</h2>
          <div className="flex flex-wrap gap-2">
            {data.tags.map((tag) => (
              <span key={tag} className="rounded-full bg-gray-100 px-3 py-1 text-sm text-gray-700">
                {tag}
              </span>
            ))}
          </div>
        </div>
      </div>

      <div className="rounded-lg border p-4">
        <h2 className="mb-4 text-lg font-semibold">Positions</h2>
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead>
              <tr className="border-b text-gray-500">
                <th className="pb-3 pr-4 font-medium">Symbol</th>
                <th className="pb-3 pr-4 font-medium">Quantity</th>
                <th className="pb-3 font-medium">Avg Cost</th>
              </tr>
            </thead>
            <tbody>
              {data.positions.map((position) => (
                <tr key={position.symbol} className="border-b last:border-0">
                  <td className="py-3 pr-4 font-medium text-gray-900">{position.symbol}</td>
                  <td className="py-3 pr-4 text-gray-700">{position.qty.toLocaleString()}</td>
                  <td className="py-3 text-gray-700">¥{position.avg_cost.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
"""


def main() -> None:
    settings = Settings.from_env()
    source_repo_b_path = Path(settings.repo_b_local_path).resolve()

    print("=== Repo A snapshot demo start ===")
    config_reader = RepoBConfigReader(source_repo_b_path)
    repo_config = config_reader.load_all_config()
    default_branch = repo_config.project["git"]["default_branch"]
    branch_prefix = repo_config.project["git"]["working_branch_prefix"]
    timestamp = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    new_branch = f"{branch_prefix}{BRANCH_SLUG}-{timestamp}"

    with TemporaryDirectory(prefix="agentsystem-snapshot-demo-", ignore_cleanup_errors=True) as tmp:
        repo_b_path = _prepare_clean_checkout(source_repo_b_path, Path(tmp), default_branch)
        git = GitAdapter(repo_b_path)
        git.checkout_main_and_pull(default_branch)
        git.create_new_branch(new_branch)
        print(f"[OK] Working branch: {new_branch}")

        _apply_snapshot_changes(repo_b_path)
        print("[OK] Updated backend mock and agent page")

        shell = ShellExecutor(repo_b_path)
        install_success, install_output = shell.run_commands(repo_config.commands.get("install", []))
        if not install_success:
            raise RuntimeError(f"Install failed:\n{install_output}")
        print("[OK] Install completed")

        lint_success, lint_output = shell.run_commands(repo_config.commands["lint"])
        if not lint_success:
            raise RuntimeError(f"Lint failed:\n{lint_output}")
        print("[OK] Lint passed")

        typecheck_commands = repo_config.commands.get("typecheck", [])
        if typecheck_commands:
            typecheck_success, typecheck_output = shell.run_commands(typecheck_commands)
            if not typecheck_success:
                raise RuntimeError(f"Typecheck failed:\n{typecheck_output}")
            print("[OK] Typecheck passed")

        git.add_and_commit(COMMIT_MESSAGE)
        git.push_branch(new_branch)
        print("[OK] Branch pushed to origin")

        if not settings.github_token or not settings.github_owner or not settings.github_repo_b_name:
            raise RuntimeError("Missing GitHub config in .env")
        pr = GitHubPullRequestAdapter(
            token=settings.github_token,
            owner=settings.github_owner,
            repo_name=settings.github_repo_b_name,
        )
        pr_url = pr.create_pull_request(
            title=PR_TITLE,
            body=PR_BODY,
            head_branch=new_branch,
            base_branch=default_branch,
        )
        print(f"[OK] PR created: {pr_url}")

    print("=== Repo A snapshot demo completed ===")


def _apply_snapshot_changes(repo_b_path: Path) -> None:
    agent_registry_path = repo_b_path / "apps" / "api" / "src" / "domain" / "agent_registry" / "service.py"
    agent_page_path = repo_b_path / "apps" / "web" / "src" / "app" / "(dashboard)" / "agents" / "[agentId]" / "page.tsx"

    agent_registry_path.write_text(UPDATED_AGENT_REGISTRY, encoding="utf-8")
    agent_page_path.write_text(UPDATED_AGENT_PAGE, encoding="utf-8")


def _prepare_clean_checkout(source_repo_b_path: Path, working_root: Path, default_branch: str) -> Path:
    source_repo = Repo(source_repo_b_path)
    clone_target = working_root / "repo_b"
    remote_url = source_repo.remotes.origin.url if source_repo.remotes else None

    if source_repo.remotes:
        source_repo.git.fetch("origin", default_branch)
        active_branch = source_repo.active_branch.name if not source_repo.head.is_detached else None
        if active_branch != default_branch:
            source_repo.git.branch("-f", default_branch, f"origin/{default_branch}")

    Repo.clone_from(str(source_repo_b_path), clone_target, branch=default_branch)
    clone_repo = Repo(clone_target)
    if remote_url:
        clone_repo.remotes.origin.set_url(remote_url)
    return clone_target


if __name__ == "__main__":
    main()
