from __future__ import annotations

DEMO_BRANCH_SLUG = "demo-update-homepage"
DEMO_COMMIT_MESSAGE = "feat: auto-update homepage subtitle (Repo A demo)"
DEMO_PR_TITLE = "[Auto] Update homepage subtitle"
DEMO_PR_BODY = (
    "This pull request was generated by Repo A. "
    "It updates the homepage subtitle and runs the configured lint checks."
)
TARGET_SENTENCE = "Agent-native finance world."
REPLACEMENT_SENTENCE = "Agent-native finance world - this line was generated by Repo A."
